name: Deploy application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar cÃ³digo
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Generar archivo JAR
      run: mvn clean package -DskipTests
      env:
        C3PO_DISCORD_SECRET: ${{ secrets.C3PO_DISCORD_SECRET }}
        INVOCADOR_DISCORD_SECRET: ${{ secrets.INVOCADOR_DISCORD_SECRET }}
        INVISIBLE_FRIEND_DISCORD_SECRET: ${{ secrets.INVISIBLE_FRIEND_DISCORD_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_USERNAME: $ {{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: $ {{ secrets.MONGODB_PASSWORD }}

    - name: Copiar archivo JAR a instancia EC2 2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./target/partygame-0.0.1-SNAPSHOT.jar"
        target: "/home/ec2-user/deploy"
          
    - name: Run Backend
      uses: appleboy/ssh-action@v1.0.2
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_USERNAME: $ {{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: $ {{ secrets.MONGODB_PASSWORD }}
        MONGODB_CLUSTER: $ {{ secrets.MONGODB_CLUSTER }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/deploy/target &&
          export MONGODB_CLUSTER=${{ secrets.MONGODB_CLUSTER }} &&
          export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} &&
          export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} &&
          export MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }} &&
          echo '' > /home/ec2-user/env/discordbot.conf &&
          echo "MONGODB_CLUSTER=$MONGODB_CLUSTER" >> /home/ec2-user/env/discordbot.conf &&
          echo "MONGODB_USERNAME=$MONGODB_USERNAME" >> /home/ec2-user/env/discordbot.conf &&
          echo "MONGODB_PASSWORD=$MONGODB_PASSWORD" >> /home/ec2-user/env/discordbot.conf &&
          echo "MONGODB_DATABASE=$MONGODB_DATABASE" >> /home/ec2-user/env/discordbot.conf &&
          echo "Stop partygame.service" &&
          ls &&
          sudo systemctl stop partygame.service &&
          echo "Init partygame.service" &&
          sudo systemctl start partygame.service
          ls -al
